_target_: src.models.flow_matching_module.SetFlowMatchingLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  weight_decay: 0.00005

#scheduler:
#  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
#  _partial_: true
#  T_max: 5000

scheduler:
  _target_: src.schedulers.lr_scheduler.CosineWarmupScheduler
  _partial_: true
  warmup: 1000
  max_iters: 10000

features: 3
n_transforms: 1
layers: 10
hidden_dim: 256
latent: 256
activation: leaky_relu
wrapper_func: weight_norm
dropout: 0.0
sum_scale: 1e-2

t_emb: cosine
frequencies: 16
t_global_cat: True
t_local_cat: True
add_time_to_input: False

loss_type: 'FM-OT'
diff_config:
  max_sr: 0.999
  min_sr: 0.02
criterion: 'mse'
sigma: 1e-4

use_normaliser: False
normaliser_config:
  max_n: 2000
