# Generate data, calculate plots and metrics and log them to the logger
jetclass_eval:
  _target_: src.callbacks.jetclass_eval.JetClassEvaluationCallback
  every_n_epochs: 100 # evaluate every n epochs
  additional_eval_epochs: [1, 20, 50, 80] # evaluate at these epochs as well
  num_jet_samples: 50_000 # jet samples to generate for evaluation
  # image_path: ${paths.log_dir}callback_logs/  # if not set, will default to trainer.default_root_dir/plots
  model_name: "epic_fm_jetclass"
  use_ema: True
  log_times: True
  log_epoch_zero: False
  data_type: "test"
  w_dist_config:
    num_eval_samples: 10_000
    num_batches: 40
    calculate_efps: False
  generation_config:
    batch_size: 1_000
    ode_solver: "midpoint"
    ode_steps: 200
    verbose: False
  plot_config:
    plot_efps: False
